# 密钥配置
rsakey:
  public_keyfile: "./keys/public.key"
  private_keyfile: "./keys/private.pem"

# 服务器设置
servers:
  - name: "Official"
    root_url: "https://mojang.com"
    api_type: "mojang"
    enabled: true
  - name: "AI-Hobbyist"
    root_url: "https://api.aihmc.top"
    api_type: "aihmc"
    enabled: true
  - name: "LittleSkin"
    root_url: "https://littleskin.cn"
    api_type: "blessingskin"
    enabled: true  
  - name: "Ely.by"
    root_url: "https://ely.by"
    api_type: "elyby"
    enabled: true

extra_skin_domains:
  - ".minecraft.net"
  - "minecraft.net"

# 数据库设置
database:
  host: "127.0.0.1" 
  port: 3306
  user: "root"
  password: ""
  db_name: "aihmc_auth"

#服务端设置
server:
  host: "0.0.0.0"
  port: 8002
  debug: false
  timeout: 5.0

# 允许离线登录验证
allow_offline: true

# Figura会话有效期
figura_session: 2d

# 访问令牌
access_token: ""
